/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminJPanels;

import Business.Business;
import Hospital.Appointment;
import Insurance.InsuranceEnrollment;
import Prescription.Prescription;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MC
 */
public class EnterpriseReportingJPanel extends javax.swing.JPanel {

    public Business business;
    
    public EnterpriseReportingJPanel(Business business) {
        initComponents();
        this.business = business;
        
        //Hospital
        
        ArrayList<Appointment> apts = this.business.getAppointments().getAppointments();
        int totalAppointments = apts.size();
        Float totalRevenue = 0.00f;
        
        for (Appointment a : apts)
        {
            totalRevenue = totalRevenue + a.getCost();
        }
        
        hospTotalRevenue.setText(totalRevenue.toString());
        hosNumAptsLabel.setText(String.valueOf(totalAppointments));
        
        //Pharmacy
        
        ArrayList<Prescription> ps = this.business.getPrescriptions().getPrescriptions();
        int totalPrescriptions = ps.size();
        Float pharTotalRevenue = 0.00f;
        
        for (Prescription p : ps)
        {
            pharTotalRevenue = pharTotalRevenue + (p.getMedicine().getPrice() * p.getQuantity());
        }
        
        phNumTestsLabel.setText(pharTotalRevenue.toString());
        phRevenueLabel.setText(String.valueOf(totalPrescriptions));
        
        //Insurance
        
        ArrayList<InsuranceEnrollment> ie = this.business.getInsuranceEnrollmentRequests().getEnrollments();
        int totalPlansSold = 0;
        Float insTotalRevenue = 0.00f;
        
        for (InsuranceEnrollment i : ie)
        {
            if(!"Approved".equals(i.getStatus()))
            {
                continue;
            }
            
            totalPlansSold = totalPlansSold + 1;
            insTotalRevenue = insTotalRevenue + i.getInsurancePlan().getCostperAnnum();
        }
        
        insRevenueLabel.setText(insTotalRevenue.toString());
        plansSoldLabel.setText(String.valueOf(totalPlansSold));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hospTotalRevenue = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        plansSoldLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        insRevenueLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phNumTestsLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phRevenueLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hosNumAptsLabel = new javax.swing.JLabel();

        jLabel1.setText("Hospital");

        jLabel2.setText("Pharmacy");

        jLabel3.setText("Insurance");

        jLabel4.setText("Lab");

        jLabel5.setText("Total Revenue");

        hospTotalRevenue.setText("jLabel6");

        jLabel6.setText("Num of Plans Sold");

        plansSoldLabel.setText("jLabel7");

        jLabel7.setText("Total Revenue");

        insRevenueLabel.setText("jLabel8");

        jLabel10.setText("Total No Of Tests");

        phNumTestsLabel.setText("jLabel11");

        jLabel9.setText("Revenue");

        phRevenueLabel.setText("jLabel11");

        jLabel11.setText("Num of Appointments");

        hosNumAptsLabel.setText("jLabel12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(368, 368, 368)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insRevenueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plansSoldLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hosNumAptsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(hospTotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phRevenueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(phNumTestsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hospTotalRevenue)
                    .addComponent(jLabel10)
                    .addComponent(phNumTestsLabel))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(phRevenueLabel)
                    .addComponent(jLabel11)
                    .addComponent(hosNumAptsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(plansSoldLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(insRevenueLabel))
                .addGap(141, 141, 141))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hosNumAptsLabel;
    private javax.swing.JLabel hospTotalRevenue;
    private javax.swing.JLabel insRevenueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel phNumTestsLabel;
    private javax.swing.JLabel phRevenueLabel;
    private javax.swing.JLabel plansSoldLabel;
    // End of variables declaration//GEN-END:variables
}
