/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.InsuranceJPanels;

import Business.Business;
import Insurance.InsuranceAgent.ApplicantDirectory;
import Insurance.InsuranceAgent.CreateApplicant;
import Insurance.Plans.InsurancePlans;
import UserAccount.UserAccount;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author divya
 */
public class CreateApplicantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateApplicantJPanel
     */
    Business business;
    UserAccount useraccount;
     private CreateApplicant applicant;
      ApplicantDirectory applicantDirectory;
    public CreateApplicantJPanel() {
        initComponents();
        populateDropDown();
    }
      public CreateApplicantJPanel(Business business,UserAccount useraccount,ApplicantDirectory applicantDirectory) {
        initComponents();
        populateDropDown();
        this.business=business;
        this.useraccount=useraccount;
        this.applicantDirectory=applicantDirectory;
    }
    
public void populateDropDown(){
    
    
    planComboBox.removeAllItems();
        
        for(InsurancePlans d: this.business.getPlanDirectory().getPlansDirectory()){
            planComboBox.addItem(d.getPlanName());
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fappID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fFirstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fLastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fdate = new com.toedter.calendar.JDateChooser();
        getDateBtn = new javax.swing.JButton();
        ftdate = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fMobileNumber = new javax.swing.JTextField();
        fGender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fSSN = new javax.swing.JTextField();
        fAge = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        planComboBox = new javax.swing.JComboBox();
        applicantDetailsBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setText("Create Applicant Details");

        jLabel3.setText("Application ID");

        fappID.setEditable(false);

        jLabel2.setText("First Name");

        jLabel5.setText("Last Name");

        jLabel6.setText("Application Date");

        getDateBtn.setText("get Date");
        getDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDateBtnActionPerformed(evt);
            }
        });

        ftdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftdateActionPerformed(evt);
            }
        });

        submitBtn.setText("submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Age");

        jLabel7.setText("mobile Number");

        fMobileNumber.setText(" ");

        fGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fGenderActionPerformed(evt);
            }
        });

        jLabel8.setText("Gender");

        jLabel9.setText("SSN");

        fSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSSNActionPerformed(evt);
            }
        });

        jLabel10.setText("Plan");

        planComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planComboBoxActionPerformed(evt);
            }
        });

        applicantDetailsBtn.setText("Applicant Details");
        applicantDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicantDetailsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fdate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitBtn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fAge, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fSSN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fGender, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fMobileNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ftdate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(planComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 186, Short.MAX_VALUE))
                            .addComponent(fLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addComponent(fappID, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(getDateBtn)
                        .addGap(134, 134, 134))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(applicantDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applicantDetailsBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fappID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(getDateBtn)
                    .addComponent(fdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ftdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(fSSN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(planComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(submitBtn)
                .addGap(43, 43, 43))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void getDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDateBtnActionPerformed
        // TODO add your handling code here:
        String txt = String.valueOf(fdate.getDate());
        ftdate.setText(txt);
    }//GEN-LAST:event_getDateBtnActionPerformed

    private void ftdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftdateActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:

        try
        {

            //int applicationID = Integer.valueOf();
            String firstName  = fFirstName.getText();

            String lastName = fLastName.getText();

            String date= ftdate.getText();
            String gender =fGender.getText();
            String Age = fAge.getText();
            String mobileNumber = fMobileNumber.getText();
            String SSN = fSSN.getText();
            String planName = planComboBox.getSelectedItem().toString();

            CreateApplicant applicant= this.business.getApplicantDirectory().addApplicant();
            //applicant.setApplicationID(applicationID);
            applicant.setFirstName(firstName);
            applicant.setLastName(lastName);
            applicant.setApplicationDate(date);
            applicant.setMobilenumber(mobileNumber);
            applicant.getAge();
            applicant.setGender(gender);
            applicant.setSSN(SSN);
            applicant.getPlans().setPlanName(planName);

            JOptionPane.showMessageDialog(this,"Added Details");

        }

        catch(HeadlessException | NumberFormatException ex){
            fappID.setText("");
            fFirstName.setText("");
            fLastName.setText("");
            ftdate.setText("");
            fAge.setText("");

            JOptionPane.showMessageDialog(null, "Please check data and try again!");

        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void fGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fGenderActionPerformed

    private void fSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fSSNActionPerformed

    private void planComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planComboBoxActionPerformed

    private void applicantDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicantDetailsBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new InsuranceAgentJFrame(business,useraccount);

    }//GEN-LAST:event_applicantDetailsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applicantDetailsBtn;
    private javax.swing.JTextField fAge;
    private javax.swing.JTextField fFirstName;
    private javax.swing.JTextField fGender;
    private javax.swing.JTextField fLastName;
    private javax.swing.JTextField fMobileNumber;
    private javax.swing.JTextField fSSN;
    private javax.swing.JTextField fappID;
    private com.toedter.calendar.JDateChooser fdate;
    private javax.swing.JTextField ftdate;
    private javax.swing.JButton getDateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox planComboBox;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
