/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminJPanels;

import Business.Business;
import Doctor.Doctor;
import Doctor.DoctorDirectory;
import Hospital.Hospital;
import Role.NurseRole;
import Role.ReceptionistRole;
import Role.Role;
import Staff.Staff;
import Staff.StaffDirectory;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MC
 */
public class StaffJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StaffJPanel
     */
    public Business business;
    DefaultTableModel staffTableModel;
    
    public StaffJPanel(Business business) {
        initComponents();
        this.business = business;
        this.staffTableModel = (DefaultTableModel) staffTable.getModel();
        
        populateHospitals();
        displayStaffMembers();
    }
    
    private void populateHospitals()
    {
        for(Hospital b : this.business.getHospitals().getHospitals())
        {
            hospCBox.addItem(b.getHospitalName());
        }
    }
    
    public void displayStaffMembers()
    {
        ArrayList<Hospital> hospitals = this.business.getHospitals().getHospitals();
        
        if(hospitals.size() >= 0) {
            staffTableModel.setRowCount(0);
            for(Hospital h: hospitals) {
                for(Staff d : h.getStaff().getStaffList())
                {
                    Object row[] = new Object[5];
                    row[0] = d.getId();
                    row[1] = d.getFirstName() + ' ' + d.getLastName();
                    row[2] = d.getRole();
                    row[3] = d.getPhoneNumber();
                    row[4] = h.getHospitalName();
                    staffTableModel.addRow(row);
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        staffFNameTextField = new javax.swing.JTextField();
        staffLNameTextField = new javax.swing.JTextField();
        staffRoleCBox = new javax.swing.JComboBox<>();
        staffPhone = new javax.swing.JTextField();
        staffEmail = new javax.swing.JTextField();
        staffAddress = new javax.swing.JTextField();
        staffExp = new javax.swing.JTextField();
        staffUName = new javax.swing.JTextField();
        staffPassword = new javax.swing.JTextField();
        addStaffBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        hospCBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Firstname");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 81, 114, -1));

        jLabel2.setText("Lastname");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 119, 114, -1));

        jLabel3.setText("Role");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 157, 114, -1));

        jLabel4.setText("Phone");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 195, 114, -1));

        jLabel5.setText("Email");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 233, 114, -1));

        jLabel6.setText("Address");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 271, 114, -1));

        jLabel7.setText("Experience");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 309, 87, -1));

        jLabel8.setText("Username");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 347, 114, -1));

        jLabel9.setText("Password");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 385, 114, -1));
        add(staffFNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 78, 163, -1));
        add(staffLNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 116, 163, -1));

        staffRoleCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nurse", "Receptionist" }));
        add(staffRoleCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 154, 163, -1));

        staffPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffPhoneActionPerformed(evt);
            }
        });
        add(staffPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 192, 163, -1));

        staffEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffEmailActionPerformed(evt);
            }
        });
        add(staffEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 230, 163, -1));
        add(staffAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 268, 163, -1));
        add(staffExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 306, 163, -1));
        add(staffUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 344, 163, -1));
        add(staffPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 382, 163, -1));

        addStaffBtn.setText("Add Staff Member");
        addStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffBtnActionPerformed(evt);
            }
        });
        add(addStaffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 526, -1, -1));

        jLabel10.setText("Hospital");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 423, 114, -1));

        add(hospCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 420, 163, -1));

        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Role", "Phone", "Hospital"
            }
        ));
        jScrollPane1.setViewportView(staffTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 78, 888, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hospital Management System");
        jPanel2.add(jLabel12);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void staffPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffPhoneActionPerformed

    private void staffEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffEmailActionPerformed

    private void addStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffBtnActionPerformed
       String firstName = staffFNameTextField.getText();
       String lastName = staffLNameTextField.getText();
       String phone = staffPhone.getText();
       String email = staffEmail.getText();
       String address = staffAddress.getText();
       String role = staffRoleCBox.getSelectedItem().toString();
       Float experience = Float.valueOf(staffExp.getText());
       String userName = staffUName.getText();
       String password = staffPassword.getText();
       
       String hospName = hospCBox.getSelectedItem().toString();
       
       Role currentRole;
       
       if (role.equals("Nurse"))
       {
           currentRole = new NurseRole();
       }
       else
       {
           currentRole = new ReceptionistRole();
       }
       
       Hospital hospital = this.business.getHospitals().findHospitalByName(hospName);
       StaffDirectory staff = hospital.getStaff();
       Staff s = staff.addStaffMember(hospital, firstName, lastName, email, phone, address, currentRole, experience);
       
       //create a useraccount and add it to the top level dir
        UserAccount ua = new UserAccount();
        ua.setUsername(userName);
        ua.setPassword(password);
        ua.setRole(currentRole);
        ua.setPersonId(s.getId());
        //staff.setUserAcc(ua);

        this.business.getTopLevelUserAccountDirectory().getUseraccountList().add(ua);
        displayStaffMembers();
       
       JOptionPane.showMessageDialog(null, "Doctor registered successfully!");
    }//GEN-LAST:event_addStaffBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffBtn;
    private javax.swing.JComboBox<String> hospCBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField staffAddress;
    private javax.swing.JTextField staffEmail;
    private javax.swing.JTextField staffExp;
    private javax.swing.JTextField staffFNameTextField;
    private javax.swing.JTextField staffLNameTextField;
    private javax.swing.JTextField staffPassword;
    private javax.swing.JTextField staffPhone;
    private javax.swing.JComboBox<String> staffRoleCBox;
    private javax.swing.JTable staffTable;
    private javax.swing.JTextField staffUName;
    // End of variables declaration//GEN-END:variables
}
