/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Nurse;

import Business.Business;
import Doctor.Doctor;
import Hospital.Appointment;
import Hospital.Hospital;
import Hospital.Vitals;
import Patient.Patient;
import UserAccount.UserAccount;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MC
 */
public class VitalsJPanel extends javax.swing.JPanel {

    public Business business;
    public UserAccount userAccount;
    DefaultTableModel vitalsTableModel;
    
    public VitalsJPanel() {
        initComponents();
    }
    
    public VitalsJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        this.vitalsTableModel = (DefaultTableModel) nurVitalsTable.getModel();
        
        //displayVitals();
        populateDropdowns();
    }
    
    public void populateDropdowns()
    {
        for (Patient p : this.business.getPatients().getPatientList())
        {
            selPatientCBox.addItem(p.getId() + ';' + p.getFirstName() + ' ' + p.getLastName());
        }
    }
    
    public void displayVitals(String patientId)
    {
        Patient p = this.business.getPatients().findPatient(patientId);
        ArrayList<Vitals> vitals = p.getVitals().getVitalsList();
        if(vitals.size() >= 0) {
            vitalsTableModel.setRowCount(0);
            for(Vitals v: vitals) {
                Object row[] = new Object[7];
                row[0] = p.getFirstName()+ ' ' + p.getLastName();
                row[1] = v.getVitalId();
                row[2] = v.getBloodPressure();
                row[3] = v.getHeartRate();
                row[4] = v.getWeight();
                row[5] = v.getHeight();
                row[6] = v.getRecordedDate();
                vitalsTableModel.addRow(row);
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selPatientCBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        bpTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hrTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        heightTextField = new javax.swing.JTextField();
        recordVital = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nurVitalsTable = new javax.swing.JTable();
        viewVitalsBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setText("Select a Patient");

        jLabel2.setText("Blood Pressure");

        jLabel3.setText("Heart rate");

        jLabel4.setText("Weight");

        jLabel5.setText("Height");

        recordVital.setText("Record Details");
        recordVital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordVitalActionPerformed(evt);
            }
        });

        nurVitalsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Vital Id", "BP", "HR", "Weight", "Height", "Recorded Date"
            }
        ));
        jScrollPane1.setViewportView(nurVitalsTable);

        viewVitalsBtn.setText("View Vitals");
        viewVitalsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalsBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hospital Management System");
        jPanel2.add(jLabel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recordVital, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selPatientCBox, 0, 163, Short.MAX_VALUE)
                                    .addComponent(bpTextField)
                                    .addComponent(hrTextField)
                                    .addComponent(weightTextField)
                                    .addComponent(heightTextField))
                                .addGap(53, 53, 53)
                                .addComponent(viewVitalsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selPatientCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewVitalsBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(recordVital)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewVitalsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalsBtnActionPerformed
        String patientId = selPatientCBox.getSelectedItem().toString().split(";")[0];
        //Patient p = this.business.getPatients().findPatient(patientId);
        displayVitals(patientId);    
    }//GEN-LAST:event_viewVitalsBtnActionPerformed

    private void recordVitalActionPerformed(java.awt.event.ActionEvent evt) {                                            

        try {
            String patientId = selPatientCBox.getSelectedItem().toString().split(";")[0];

            Patient p = this.business.getPatients().findPatient(patientId);

            String bp = bpTextField.getText();
            int hr = Integer.parseInt(hrTextField.getText());
            Float weight = Float.valueOf(weightTextField.getText());
            Float height = Float.valueOf(heightTextField.getText());
            if (bpTextField.getText().equals("") || hrTextField.getText().equals("") || weightTextField.getText().equals("") || heightTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please check data and try again!");
            } else {
                p.getVitals().addVital(p, bp, hr, weight, height);
                displayVitals(patientId);
            }

        } catch (HeadlessException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please check data and try again!");
        }
        bpTextField.setText("");

        hrTextField.setText("");
        weightTextField.setText("");
        heightTextField.setText("");

    }                                            


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bpTextField;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JTextField hrTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable nurVitalsTable;
    private javax.swing.JButton recordVital;
    private javax.swing.JComboBox<String> selPatientCBox;
    private javax.swing.JButton viewVitalsBtn;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
